apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: web-grading
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          imagePullPolicy: IfNotPresent
          args:
            - start-dev
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: KEYCLOAK_DB_URL
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: KEYCLOAK_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: KEYCLOAK_DB_PASSWORD
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: KEYCLOAK_ADMIN_USERNAME
                  optional: true
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db
                  key: KEYCLOAK_ADMIN_PASSWORD
                  optional: true
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: "https://web-dev1-keycloak.vucongtuanduong.dpdns.org"
            - name: KC_HOSTNAME_ADMIN
              value: "https://web-dev1-keycloak.vucongtuanduong.dpdns.org"
