apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otlp
  namespace: observability
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: web-dev1-otlp.vucongtuanduong.dpdns.org
      http:
        paths:
          - path: /v1/
            pathType: Prefix
            backend:
              service:
                name: alloy
                port:
                  number: 4318