#!/bin/bash

echo "==============================================="
echo "  Manual Step: Delete GitHub Release v1.0.1"
echo "==============================================="
echo ""
echo "⚠️  IMPORTANT: You need to manually delete the GitHub Release!"
echo ""
echo "Steps:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://github.com/Duong-Vu-practice-workspace/web-grading-system-services-test/releases"
echo ""
echo "2. Find release: 'submission-service v1.0.1'"
echo ""
echo "3. Click on the release"
echo ""
echo "4. Click 'Delete' button (trash icon) on the right"
echo ""
echo "5. Confirm deletion"
echo ""
echo "==============================================="
echo ""
echo "After deleting the release, run:"
echo "  cd src-services"
echo "  git push origin main"
echo ""
echo "This will trigger workflow to create v1.0.2!"
echo ""
echo "==============================================="
